# Generated by Django 4.2.27 on 2026-02-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
    ]

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("itineraries", "Category")

    categories = [
        "Sights",
        "Flavours",
        "Experiences",
        "Culture",
        "Seasons",
    ]

    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
