# Generated by Django 4.2.27 on 2026-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='user_note',
            field=models.TextField(blank=True),
        ),
    ]
