# Generated by Django 4.2.27 on 2026-02-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_trip'),
        ('itineraries', '0005_auto_20260224_2032'),
    ]

    operations = [
    ]
