# Generated by Django 4.2.27 on 2026-02-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_alter_category_options_category_display_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
