# Generated by Django 4.2.27 on 2026-02-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_headers/'),
        ),
    ]
