# Generated by Django 4.2.27 on 2026-02-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_category_description_category_header_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
