# Generated by Django 4.2.27 on 2026-03-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_delete_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['display_order']},
        ),
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='description',
            new_name='story_description',
        ),
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='title',
            new_name='story_title',
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.category'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='user_note',
            field=models.TextField(blank=True, help_text='Optional personal notes'),
        ),
    ]
