# Generated by Django 4.2.27 on 2026-03-06 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_alter_itineraryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
