# Generated by Django 4.2.27 on 2026-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itineraryitem_created_on_itineraryitem_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='context_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='context_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
