# Generated by Django 4.2.27 on 2026-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_category_context_subtitle_category_context_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryitem',
            unique_together={('itinerary', 'display_order')},
        ),
    ]
