# Generated by Django 4.2.27 on 2026-03-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_alter_itinerary_description_alter_itinerary_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
