# Generated by Django 4.2.27 on 2026-03-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0015_alter_category_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='context_subtitle',
        ),
        migrations.AddField(
            model_name='category',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
