# Generated by Django 4.2.27 on 2026-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0016_remove_category_context_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snow'), ('night', 'Night')], max_length=10),
        ),
    ]
