# Generated by Django 4.2.27 on 2026-03-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0017_category_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='day_night',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=5),
        ),
    ]
