# Generated by Django 4.2.27 on 2026-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0018_category_day_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
