# Generated by Django 4.2.27 on 2026-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0019_alter_itinerary_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='country_code',
            field=models.CharField(default='XX', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country_name',
            field=models.CharField(default='XX', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='slug',
            field=models.SlugField(blank=True, default='--', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
