# Generated by Django 4.2.27 on 2026-03-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0020_itinerary_country_code_itinerary_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snowy'), ('cloud', 'Cloudy'), ('wind', 'Windy'), ('night', 'Night')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
