# Generated by Django 4.2.27 on 2026-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0021_alter_category_weather_alter_itinerary_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='context_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='day_night',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='weather',
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='context_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='context_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='day_night',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=5),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snowy'), ('wind', 'Windy')], max_length=10),
        ),
    ]
