# Generated by Django 4.2.27 on 2026-03-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tripitem_date_tripitem_story_description_and_more'),
        ('itineraries', '0022_remove_category_context_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_itineraries', to='trips.trip'),
        ),
    ]
