# Generated by Django 4.2.27 on 2026-03-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraries', '0023_itinerary_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='original_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
