# Generated by Django 4.2.27 on 2026-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0024_itinerary_original_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='day_night',
            field=models.CharField(choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=50),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snowy'), ('wind', 'Windy'), ('storm', 'Stormy')], max_length=10),
        ),
    ]
