# Generated by Django 4.2.27 on 2026-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0025_alter_itineraryitem_day_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='day_night',
            field=models.CharField(choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=10),
        ),
    ]
