# Generated by Django 4.2.27 on 2026-05-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0026_alter_itineraryitem_day_night'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryitem',
            unique_together=set(),
        ),
    ]
