# Generated by Django 4.2.27 on 2026-03-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0018_category_day_night'),
        ('trips', '0002_tripitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='tripitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itineraries.category'),
        ),
    ]
