# Generated by Django 4.2.27 on 2026-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
