# Generated by Django 4.2.27 on 2026-03-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='slug',
        ),
    ]
