# Generated by Django 4.2.27 on 2026-03-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_slug'),
        ('trips', '0005_remove_trip_slug'),
    ]

    operations = [
    ]
