# Generated by Django 4.2.27 on 2026-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_merge_0005_alter_trip_slug_0005_remove_trip_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='slug',
        ),
    ]
