# Generated by Django 4.2.27 on 2026-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_story_description_trip_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
