# Generated by Django 4.2.27 on 2026-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_date_trip_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='story_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='story_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='weather',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
