# Generated by Django 4.2.27 on 2026-03-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tripitem_date_tripitem_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
