# Generated by Django 4.2.27 on 2026-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trip_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
    ]
