# Generated by Django 4.2.27 on 2026-03-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_tripitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='country_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
