# Generated by Django 4.2.27 on 2026-04-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_trip_country_code_trip_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripitem',
            old_name='date',
            new_name='travel_date',
        ),
        migrations.AddField(
            model_name='tripitem',
            name='day_night',
            field=models.CharField(blank=True, choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], max_length=10),
        ),
    ]
