# Generated by Django 4.2.27 on 2026-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_rename_date_tripitem_travel_date_tripitem_day_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
