# Generated by Django 4.2.27 on 2026-04-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_alter_trip_title_alter_tripitem_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='trip_category_headers/')),
            ],
            options={
                'verbose_name_plural': 'Trip Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='weather',
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='context_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='context_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='day_night',
            field=models.CharField(choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_items/'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='story_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='user_note',
            field=models.TextField(blank=True, help_text='Optional personal notes'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snowy'), ('wind', 'Windy'), ('storm', 'Stormy')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together={('trip', 'display_order')},
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.category'),
        ),
    ]
