# Generated by Django 4.2.27 on 2026-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_category_remove_trip_date_remove_trip_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='day_night',
            field=models.CharField(blank=True, choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather',
            field=models.CharField(blank=True, choices=[('sun', 'Sunny'), ('cloud', 'Cloudy'), ('rain', 'Rainy'), ('snow', 'Snowy'), ('wind', 'Windy'), ('storm', 'Stormy')], max_length=10),
        ),
    ]
