# Generated by Django 4.2.27 on 2026-04-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_trip_day_night_trip_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='day_night',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='title',
        ),
    ]
