# Generated by Django 4.2.27 on 2026-04-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0026_alter_itineraryitem_day_night'),
        ('trips', '0018_remove_trip_day_night_remove_trip_weather_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itineraries.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
