# Generated by Django 4.2.27 on 2026-04-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_alter_tripitem_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='story_description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='story_title',
        ),
    ]
