# Generated by Django 4.2.27 on 2026-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_remove_trip_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='story_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='story_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
