# Generated by Django 4.2.27 on 2026-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_trip_story_description_trip_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitem',
            name='day_night',
            field=models.CharField(blank=True, choices=[('sunrise', 'Sunrise'), ('day', 'Day'), ('sunset', 'Sunset'), ('night', 'Night')], default='day', max_length=10),
        ),
    ]
