# Generated by Django 4.2.27 on 2026-04-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_alter_tripitem_day_night'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together=set(),
        ),
    ]
