# Generated by Django 4.2.27 on 2026-04-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_alter_tripitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together={('trip', 'display_order')},
        ),
    ]
