# Generated by Django 4.2.27 on 2026-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_alter_tripitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitem',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
