# Generated by Django 4.2.27 on 2026-05-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_alter_tripitem_display_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together=set(),
        ),
    ]
